"""Generate and ingest market intelligence reports for POC demo.

Usage:
    python scripts/load_poc_data.py

Generates PDF reports from PROFECO API pricing data (via
generate_market_reports.py) and ingests them into the RAG knowledge base.

Note: External third-party reports were removed from this script as they
diluted search quality with irrelevant content (lab tests, outdated studies).
Only locally-generated market intelligence reports are used.
"""

import os
import sys
import time

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rag.config import DOCUMENTS_DIR
from rag.engine import RAGEngine

# No external downloads — reports are generated by generate_market_reports.py
POC_REPORTS = []


def main():
    print("=" * 60)
    print("POC Data Loader - Market Intelligence Reports")
    print("=" * 60)
    print()
    print("This script no longer downloads external reports.")
    print("Use 'python scripts/generate_market_reports.py' to generate")
    print("market intelligence PDFs from PROFECO API data.")
    print()

    engine = RAGEngine()
    if not engine.is_configured():
        print("ERROR: OpenAI API key not configured.")
        print("Set OPENAI_API_KEY in .env file")
        sys.exit(1)

    status = engine.get_status()
    print(f"Knowledge base: {status.document_count} docs, {status.total_chunks} chunks")
    print("=" * 60)


if __name__ == "__main__":
    main()
